name: absensitanggamus
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  dio: ^5.3.2
  riverpod_annotation:
  shared_preferences:
  freezed_annotation:
  json_annotation:
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  latlong2: ^0.9.0
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1
  freezed:
  json_serializable:
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
